### ISSUE TITLE
New sidebars lost section title color

### ISSUE THREAD

**Issue by robmonte** [mxthevs/vscode-one-dark-pro-monokai-darker#3]
I might be mistaken, but I think the title bars for each section in the side panels used to have a background color to easily separate each section. If I'm mistaken, I still think it would look a lot better to have a visual aid for this.

Here's what I currently see on my Mac pointing out the sections I am talking about. You can imagine with terminal output and debug output, the sections seem to blend together at-a-glance because it's just a solid color in the whole panel.
![image](https://user-images.githubusercontent.com/17119716/161365647-e219e455-ac08-4e72-ba20-45397c640419.png)

&nbsp;

I think it looked something more like this on each title before:
![image](https://user-images.githubusercontent.com/17119716/161365561-37dac7a5-f360-4910-9110-fb00f2222720.png)

**Comment by mxthevs** [comment]
Hi! Having separators between sections indeed looks a lot better! 😄  Also it is a very minimal change. It's subtle, but I think it goes well with the theme.

Before:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/46231311/161874454-2ff793f8-4e09-43c0-be87-78d4b6c35edd.png">

After:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/46231311/161874535-d6647164-b52a-44d1-976b-b4e1510cbf30.png">

**Comment by robmonte** [comment]
Looks great!!

**Comment by mxthevs** [comment]
Released in [the marketplace](https://marketplace.visualstudio.com/items?itemName=mxthevs.one-dark-pro-monokai-darker-reloaded) 🙌🏻

**Comment by robmonte** [comment]
So am I crazy or did the VSCode 1.66 update that just released change the side panel for the terminal? The background color is now the same as the text editor background and the section titles have a background color on them too. I actually like the color used on the right-side title bars.

I noticed this stuff before installing your theme fork. Is this what yours looks like on the latest version of VSCode?
![image](https://user-images.githubusercontent.com/17119716/162068581-8f16f1cb-8d8f-4286-a1f6-d17147b005f2.png)
